spring:
  application:
    name: "configserver"
  profiles:
    active: git
    # active: native
  cloud:
    config:
      server:
        # Git Location
        git:
          uri: "https://github.com/devemre/master-microservices-spring-docker-kubernetes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        # native:
          # Classpath Location
          # search-locations: "classpath:/config"

          # File System Location
          # search-locations: "file:///Users//...
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "12345678901234567890123456789012"

server:
  port: 8071
